# Generated by Django 4.2.1 on 2023-05-22 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, verbose_name='Order ID')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('card_number', models.CharField(max_length=100, verbose_name='Card number')),
                ('gateway_track_id', models.IntegerField(verbose_name='Gateway track ID')),
                ('bank_track_id', models.CharField(max_length=100, verbose_name='Bank track ID')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
