# Generated by Django 4.2.1 on 2023-06-30 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='Order ID')),
                ('transaction_id', models.CharField(max_length=255, verbose_name='Transaction ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('card_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Card number')),
                ('gateway_track_id', models.IntegerField(blank=True, null=True, verbose_name='Gateway track ID')),
                ('bank_track_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank track ID')),
                ('status', models.IntegerField(choices=[(1, 'Payment has not been made'), (2, 'Payment has failed'), (3, 'An error has occurred'), (4, 'blocked'), (5, 'Return to payer'), (6, 'Systemic backlash'), (7, 'Cancellation of payment'), (8, 'Moved to the payment gateway'), (10, 'Awaiting payment confirmation'), (100, 'Payment is confirmed'), (101, 'Payment has already been confirmed'), (200, 'It was deposited to the recipient')], default=8, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
