# Generated by Django 4.2.1 on 2023-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_track_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank track ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway_track_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gateway track ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Payment has not been made'), (2, 'Payment has failed'), (3, 'An error has occurred'), (4, 'blocked'), (5, 'Return to payer'), (6, 'Systemic backlash'), (7, 'Cancellation of payment'), (8, 'Moved to the payment gateway'), (10, 'Awaiting payment confirmation'), (100, 'Payment is confirmed'), (101, 'Payment has already been confirmed'), (200, 'It was deposited to the recipient')], default=8, verbose_name='Status'),
        ),
    ]
