# Generated by Django 4.2.1 on 2023-05-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('real_link', models.URLField(verbose_name='Real link')),
                ('token', models.CharField(max_length=10, unique=True, verbose_name='Token')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('clicks_count', models.IntegerField(default=0, verbose_name='Clicks count')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Is deleted')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
